export const WORKOUT_OPTIONS = [
  { id: 'pushup',        label: 'Push-Ups',        icon: 'fitness_center',              cue: 'Get into push-up position on the floor.'              },
  { id: 'squat',         label: 'Squats',            icon: 'accessibility_new',           cue: 'Stand with feet shoulder-width apart.'                },
  { id: 'plank',         label: 'Plank',             icon: 'horizontal_rule',             cue: 'Get into a plank position facing the camera.'         },
  { id: 'lunge',         label: 'Lunges',            icon: 'directions_walk',             cue: 'Stand upright. Step forward alternating legs.'        },
  { id: 'overhead',      label: 'OH Press',          icon: 'upload',                      cue: 'Stand tall, arms at shoulder height.'                 },
  { id: 'dip',           label: 'Dips',              icon: 'unfold_more',                 cue: 'Position behind a chair or bench for dips.'          },
  { id: 'burpee',        label: 'Burpees',           icon: 'bolt',                        cue: 'Stand in the centre of the frame.'                    },
  { id: 'jumpingjack',   label: 'Jumping Jacks',     icon: 'sports_gymnastics',           cue: 'Stand upright with feet together.'                    },
  { id: 'mountainclimb', label: 'Mountain Climbers', icon: 'terrain',                     cue: 'Get into a high plank facing the camera.'             },
  { id: 'highknee',      label: 'High Knees',        icon: 'directions_run',              cue: 'Stand tall and run on the spot, lifting knees high.'  },
  { id: 'glute_bridge',  label: 'Glute Bridge',      icon: 'airline_seat_flat',           cue: 'Lie on your back with knees bent.'                    },
  { id: 'crunch',        label: 'Crunches',          icon: 'airline_seat_recline_normal', cue: 'Lie on your back, knees bent, feet flat.'            },
  { id: 'situp',         label: 'Sit-Ups',           icon: 'self_improvement',            cue: 'Lie on your back, knees bent, feet flat.'            },
  { id: 'bicep_curl',    label: 'Bicep Curls',       icon: 'sports_mma',                  cue: 'Stand upright, arms at sides holding weights.'        },
  { id: 'tricep_ext',    label: 'Tricep Ext.',       icon: 'back_hand',                   cue: 'Stand or sit, arm extended overhead.'                 },
  { id: 'lateral_raise', label: 'Lateral Raise',     icon: 'open_with',                   cue: 'Stand with arms at sides.'                            },
  { id: 'deadlift',      label: 'Deadlift',          icon: 'arrow_downward',              cue: 'Stand with feet hip-width apart, weight in front.'    },
  { id: 'hip_thrust',    label: 'Hip Thrust',        icon: 'chair',                       cue: 'Back against bench, feet flat on floor.'             },
  { id: 'sideplank',     label: 'Side Plank',        icon: 'rotate_90_degrees_cw',        cue: 'Lie on your side and prop up on one forearm.'        },
  { id: 'boxjump',       label: 'Box Jumps',         icon: 'upload_file',                 cue: 'Stand in front of the box, camera to your side.'     },
  { id: 'pullup',        label: 'Pull-Ups',          icon: 'keyboard_arrow_up',           cue: 'Hang from the bar, camera facing you.'                },
  { id: 'calfraise',     label: 'Calf Raises',       icon: 'footprint',                   cue: 'Stand upright near a wall for balance.'               },
];
